version: '3'


services:
    db: 
      image: postgres:14.3
      restart: always 
      ports:
        - "6432:5432"
      environment:
        POSTGRES_PASSWORD: ${DB_PASSWORD}
        POSTGRES_USER: ${DB_USER}
        POSTGRES_DB: ${DB_NAME}
        PGDATA: var/lib/postgresql/data/pgdata
      container_name: E-commerce
      volumes:
        - ./postgres:/var/lib/postgresql
      